### NUMPY ADVANCE CLASS ###

In [1]:
import numpy as np

print(np.__version__)

2.2.6


### NUMPY OPERATION & MULTI DYMENTION NUMPY ARRAY ###

In [2]:
''' Indexing
- Non Negetive {1,2,3}
- Negetive {-1,-2,-3}
'''
indexarray=np.array([1,2,3,4,5])

print(indexarray[1])
print(indexarray[-1])

2
5


In [3]:
''' Slicing 
- Three peremeter(start, stop, step)
- 2 Dymention-(colum,row)
'''
slicingarray1=np.array([1,2,3,4,5,6,7,8]) # 1 dymention
slicingarray2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]) # 2 dymention

print(slicingarray1[1:6:1])

print(slicingarray2[0:len(slicingarray2):1,2:3:1])

[2 3 4 5 6]
[[ 3]
 [ 8]
 [13]]


In [4]:
''' Reshape '''
reshapenp=np.ones(
    shape=(3,5)
)
reshapenp2=reshapenp.reshape(5,3)

print(reshapenp)
print(reshapenp.shape)
print(reshapenp2)
print(reshapenp2.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(3, 5)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(5, 3)


In [5]:
''' Reshape with -1 '''
np_array=np.zeros(shape=(3,4,2,2))
np_array2=np_array.reshape(2,-1,12)
print(np_array2)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [6]:
''' Filtering 
- like Conditional Statement
- BroadCasting
- Vactorization
'''
filterarray=np.array([1,2,3,4,5])

filterMask=[False,True,False,True,False] # step1
print(filterarray[filterMask]) # 2, 4

indices=[1,3] # step2
print(filterarray[indices]) # 2, 4

filterarray2=filterarray % 2 == 1
print(filterarray2) # [True, False .....]


[2 4]
[2 4]
[ True False  True False  True]


### NUMPY RANDOM ###

In [7]:
''' rand '''
randomtest1=np.random.rand(5,5)
print(randomtest1)
print(randomtest1.dtype)

randomtest2=np.random.randint(100,size=(5,2)) # size (row , colum)
print(randomtest2)
print(randomtest2.dtype)


[[0.93151602 0.59023272 0.0227858  0.81564907 0.22837691]
 [0.21749075 0.34838552 0.00600309 0.17320569 0.58695141]
 [0.88185351 0.06353025 0.39375578 0.14185748 0.95523131]
 [0.33399641 0.88625808 0.58963786 0.75681656 0.92846533]
 [0.36910584 0.97291515 0.44934044 0.03959109 0.29161347]]
float64
[[27 23]
 [67 46]
 [22 46]
 [47 62]
 [96 12]]
int32


In [8]:
# shuffle
np_array_new=np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9],
     [10,11,12]]
)
print(np_array_new)
np.random.shuffle(np_array_new)
print(np_array_new)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[10 11 12]
 [ 7  8  9]
 [ 1  2  3]
 [ 4  5  6]]


In [9]:
''' Numpy sort and sort reverse '''
sort_array=np.array([3,2,7,5,1,2,10,54])
sortarray1=np.sort(sort_array) # lower to upper
print(sortarray1)

reversearray=sortarray1[::-1]
print(reversearray)

[ 1  2  2  3  5  7 10 54]
[54 10  7  5  3  2  2  1]


In [10]:
''' maximum and minimum Number '''
Testing_Array=np.array([1,2,32,4,5,20,31,54,7,8])

max_num=np.argmax(Testing_Array)
min_num=np.argmin(Testing_Array)
print(Testing_Array[max_num])
print(Testing_Array[min_num])

54
1


In [11]:
''' split in Numpy '''
testing_Array2=np.array([1,2,3,4,5,6])

splitArray=np.split(
    testing_Array2,
    indices_or_sections=3 # Numpy Keyword
)
print(splitArray)
print(splitArray[0])
print(splitArray[1])
print(splitArray[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


### NUMPY AXIS ###

In [12]:
''' Sumation '''
sum_array=np.array(
    [[1,2,3,4,5],
     [5,4,3,2,1],
     [9,8,7,6,5]]
)
total=np.sum(sum_array) # All number sumation
row_total=np.sum(sum_array,axis=0) # row wise sumation
colum_total=np.sum(sum_array,axis=1) # colum wise sumation
print(total)
print(row_total)
print(colum_total)

65
[15 14 13 12 11]
[15 15 35]


In [13]:
npArray=np.ones(
    shape=(5,2,4)
)
print(npArray)
print(npArray.ndim)
sumation=np.sum(npArray,axis=2)
print(sumation)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3
[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]


### USEFULL PROPERTY IN NUMPY ###

In [14]:
''' dot '''
dot_array1=np.array([1,6,10])
dot_array2=np.array([2,5,9])

result=np.dot(dot_array1,dot_array2)
print(result)

122


In [15]:
''' matrix Transpose '''
np_2d_array=np.array(
    [[2,3,4],
     [6,7,8],
     [1,6,0],
     [4,6,8]]
)

print(np_2d_array.shape)
print(np_2d_array.T)
print(np_2d_array.T.shape)

(4, 3)
[[2 6 1 4]
 [3 7 6 6]
 [4 8 0 8]]
(3, 4)


In [16]:
''' mean, median, std '''
three_test1=np.array(
    [3,4,1,7,3] 
)

three_test2=np.array(
    [[1,2,3,4,5],
     [6,7,8,9,1],
     [2,4,6,8,2],
     [1,3,5,7,9]]
)

print(np.mean(three_test1))
print(np.median(three_test1))
print(np.std(three_test1)) 

print(np.mean(three_test2))
print(np.median(three_test2))
print(np.std(three_test2))


3.6
3.0
1.9595917942265424
4.65
4.5
2.669737814842499
