  ### NUMPY FIRST CLASS ###

In [7]:
import numpy as np

# Check version
print(np.__version__)

2.2.6


In [8]:
''' Test 1 '''
firstList=[1,2,3,4,5,6]
npList1=np.array(firstList)

print(firstList)
print(npList1)
# Check type
print(type(firstList))
print(type(npList1))

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
''' Test 2 '''
np.zeros(
    shape=(1,3,5)
)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
