### NUMPY ADVANCE CLASS ###

In [1]:
import numpy as np

print(np.__version__)

2.2.6


### NUMPY OPERATION & MULTI DYMENTION NUMPY ARRAY ###

In [2]:
''' Indexing
- Non Negetive {1,2,3}
- Negetive {-1,-2,-3}
'''
indexarray=np.array([1,2,3,4,5])

print(indexarray[1])
print(indexarray[-1])

2
5


In [3]:
''' Slicing 
- Three peremeter(start, stop, step)
- 2 Dymention-(colum,row)
'''
slicingarray1=np.array([1,2,3,4,5,6,7,8]) # 1 dymention
slicingarray2=np.array(
    [[1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]]) # 2 dymention

print(slicingarray1[1:6:1])

print(slicingarray2[0:len(slicingarray2):1,2:3:1])

[2 3 4 5 6]
[[ 3]
 [ 8]
 [13]]


In [4]:
''' Reshape '''
reshapenp=np.ones(
    shape=(3,5)
)
reshapenp2=reshapenp.reshape(5,3)

print(reshapenp)
print(reshapenp.shape)
print(reshapenp2)
print(reshapenp2.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(3, 5)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(5, 3)


In [5]:
''' Reshape with -1 '''
np_array=np.zeros(shape=(3,4,2,2))
np_array2=np_array.reshape(2,-1,12)
print(np_array2)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [6]:
''' Filtering 
- like Conditional Statement
- BroadCasting
- Vactorization
'''
filterarray=np.array([1,2,3,4,5])

filterMask=[False,True,False,True,False] # step1
print(filterarray[filterMask]) # 2, 4

indices=[1,3] # step2
print(filterarray[indices]) # 2, 4

filterarray2=filterarray % 2 == 1
print(filterarray2) # [True, False .....]


[2 4]
[2 4]
[ True False  True False  True]


### NUMPY RANDOM ###

In [7]:
''' rand '''
randomtest1=np.random.rand(2,5) # guss 0 to 1 number
print(randomtest1)
print(randomtest1.dtype)

randomtest2=np.random.randint(100,size=(5,2)) # size (row , colum)
print(randomtest2)
print(randomtest2.dtype)


[[0.75693368 0.81399261 0.22880142 0.0573468  0.88820505]
 [0.5294919  0.88010275 0.37066027 0.75819122 0.77657555]]
float64
[[45 71]
 [90 43]
 [99 26]
 [79 52]
 [43 51]]
int32


In [8]:
# shuffle
np_array_new=np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9],
     [10,11,12]]
)
print(np_array_new)
np.random.shuffle(np_array_new)
print(np_array_new)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


In [9]:
''' Numpy sort and sort reverse '''
sort_array=np.array([3,2,7,5,1,2,10,54])
sortarray1=np.sort(sort_array) # lower to upper
print(sortarray1)

reversearray=sortarray1[::-1]
print(reversearray)

[ 1  2  2  3  5  7 10 54]
[54 10  7  5  3  2  2  1]


In [10]:
''' maximum and minimum Number '''
Testing_Array=np.array([1,2,32,4,5,20,31,54,7,8])

max_num=np.argmax(Testing_Array) # return indices
min_num=np.argmin(Testing_Array) # return indices
print(Testing_Array[max_num])
print(Testing_Array[min_num])

54
1


In [11]:
''' split in Numpy '''
testing_Array2=np.array([1,2,3,4,5,6])

splitArray=np.split(
    testing_Array2,
    indices_or_sections=3 # Numpy Keyword
)
print(splitArray)
print(splitArray[0])
print(splitArray[1])
print(splitArray[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


### NUMPY AXIS ###

In [12]:
''' Sumation '''
sum_array=np.array(
    [[1,2,3,4,5],
     [5,4,3,2,1],
     [9,8,7,6,5]]
)
total=np.sum(sum_array) # All number sumation
row_total=np.sum(sum_array,axis=0) # colum wise sumation
colum_total=np.sum(sum_array,axis=1) # row wise sumation
print(total)
print(row_total)
print(colum_total)

65
[15 14 13 12 11]
[15 15 35]


In [13]:
npArray=np.ones(
    shape=(5,2,4)
)
print(npArray)
print(npArray.ndim)
sumation=np.sum(npArray,axis=2)
print(sumation)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3
[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]


### USEFULL PROPERTY IN NUMPY ###

In [14]:
''' dot
(1*2)+(6*5)+(10*9)=122
'''
dot_array1=np.array([1,6,10])
dot_array2=np.array([2,5,9])

result=np.dot(dot_array1,dot_array2)
print(result)

122


In [15]:
''' matrix Transpose '''
np_2d_array=np.array(
    [[2,3,4],
     [6,7,8],
     [1,6,0],
     [4,6,8]]
)

print(np_2d_array.shape)
print(np_2d_array.T) # row <--> colum
print(np_2d_array.T.shape)

(4, 3)
[[2 6 1 4]
 [3 7 6 6]
 [4 8 0 8]]
(3, 4)


In [16]:
''' mean, median, std '''
three_test1=np.array(
    [3,4,1,7,3] 
)

three_test2=np.array(
    [[1,2,3,4,5],
     [6,7,8,9,1],
     [2,4,6,8,2],
     [1,3,5,7,9]]
)

print(np.mean(three_test1))
print(np.median(three_test1))
print(np.std(three_test1)) 

print(np.mean(three_test2))
print(np.median(three_test2))
print(np.std(three_test2))


3.6
3.0
1.9595917942265424
4.65
4.5
2.669737814842499


### Data Modification

In [17]:
''' np.insert(array, index, Value, axis) 
- Cannot change original array
'''
insertArray=np.array([10,20,30,50,60])
new_array=np.insert(insertArray, 3, 40)
print(insertArray)
print(new_array)

[10 20 30 50 60]
[10 20 30 40 50 60]


In [18]:
'''
np.insert in 2 dymention array
- Cannot change original array
'''
array_2d= np.array(
    [[1,2,3,4,5],
     [7,8,9,0,5],
     [13,56,90,35,13]]
)

new_2d_arr= np.insert(array_2d, 2, [5,4,3,2,1], axis=0)

print(array_2d)
print(new_2d_arr)

[[ 1  2  3  4  5]
 [ 7  8  9  0  5]
 [13 56 90 35 13]]
[[ 1  2  3  4  5]
 [ 7  8  9  0  5]
 [ 5  4  3  2  1]
 [13 56 90 35 13]]


In [19]:
''' append
- Cannot change original array
'''
append_arr=np.array([11,12,13,14])
new_app_arr=np.append(append_arr, [15,16,17,18,19,20])

print(append_arr)
print(new_app_arr)

[11 12 13 14]
[11 12 13 14 15 16 17 18 19 20]


In [20]:
''' np.concatenate((arr1,arr2)) '''
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

concate_Arr=np.concatenate((arr1,arr2))
concate_Arr

array([1, 2, 3, 4, 5, 6])

In [21]:
''' np.delete(arr, index) '''
delete_arr=np.array([1,2,3,4,5,6])

new_del_arr=np.delete(delete_arr,5)

print(delete_arr)
print(new_del_arr)

[1 2 3 4 5 6]
[1 2 3 4 5]


In [22]:
''' np.delete() in 2d array '''
delete_arr2=np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]] 
)

new_del_arr2=np.delete(delete_arr2, 0, axis=0)
print(new_del_arr2)


[[4 5 6]
 [7 8 9]]


In [28]:
''' stack '''
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

new_Stack_arr=np.stack((arr1,arr2), axis=1)
new_Stack_arr2=np.hstack((arr1,arr2)) # use for flatten
print(new_Stack_arr)
new_Stack_arr2

[[1 4]
 [2 5]
 [3 6]]


array([1, 2, 3, 4, 5, 6])

### Handaling Missing Values

In [24]:
''' isnan 
- Detact missing values
- nan:Not A Number
'''
isnan_arr=np.array([1,2,4,5,np.nan,6,3,np.nan])

clean_isnan_data=np.isnan(isnan_arr)
print(clean_isnan_data)

[False False False False  True False False  True]


In [25]:
''' np.nan_to_num(array) 
- replace missing values
- defult value is 0
'''

replace_arr=np.array([1,2,3,np.nan,2,3,6,np.nan])
clean_replace_data=np.nan_to_num(replace_arr,nan=10)

print(clean_replace_data)

[ 1.  2.  3. 10.  2.  3.  6. 10.]


In [26]:
''' isinf
- detact infinite values
- return boolean values
- np.inf: Positive
- (-np.inf): Negetive
'''

isinf_array=np.array([1,2,3,np.inf,5,7,8,-np.inf])
detect_isinf_data=np.isinf(isinf_array)
clean_isinf_data=np.nan_to_num(isinf_array, posinf=11,neginf=-11)
print(clean_isinf_data)

[  1.   2.   3.  11.   5.   7.   8. -11.]
