  ### NUMPY FIRST CLASS ###

In [2]:
import numpy as np

# Check version
print(np.__version__)

2.2.6


In [3]:
''' Test 1 '''
firstList=[1,2,3,4,5,6]
npList1=np.array(firstList)

print(firstList)
print(npList1)
# Check type
print(type(firstList))
print(type(npList1))

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
''' Test 2 
- Create a 3 dymention list with use numpy module
- Full list amount:1
- In list item:3
- per sublist element:5
''' 
testnumpy=np.zeros(
    shape=(1,3,5)
)

print(testnumpy)
print(testnumpy.ndim)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
3


In [5]:
''' Test 3 
- shape:show how many row and colum in array
- ndim:show dymention in array
- dtype:show element data type in array
'''
testnumpy2=np.array([1,2,3,4,5])

print(testnumpy2.shape)
print(testnumpy2.ndim)
print(testnumpy2.dtype)


(5,)
1
int64


In [6]:
''' Test 4
- method of Numpy:np.ones
- shape:row3 & colum5
- All item value is 1
'''
np.ones(
    shape=(3,5)
)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
''' Test 5 
- Create a empty array
- dymention:2
- type:float
'''
test5=np.empty(
    shape=(5,0)
)
print(test5)
print(test5.shape)
print(test5.ndim)
print(test5.dtype)

[]
(5, 0)
2
float64


In [8]:
'''  Test 6 
- method of Numpy:np.full
- Create a array and all element is same 
- shape define is most important
'''

test6=np.full(
    shape=(3,3),
    fill_value=13
)
print(test6)

[[13 13 13]
 [13 13 13]
 [13 13 13]]


In [9]:
''' Test 7 
- It's called 'I3' Method
- Method of Numpy:np.eye
- Create a Dynamic number pattern
- e.g:np.eye(4)->
dimention is 2 
row is 4 
colum is 4
'''
test7=np.eye(4)
print(test7)
print(test7.ndim)
print(test7.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2
float64


In [10]:
''' Test 8
- 'Type Casting'
-  Switch Data type to Data type
'''
floatdata=np.ones(
    shape=(3,3)
)
print(f'Data Value is {floatdata} and type {floatdata.dtype}' )
intdata=floatdata.astype('int')
print(f'Data Value is {intdata} and type {intdata.dtype}')
strdata=floatdata.astype('str')
print(f'Data Value is {strdata} and type {strdata.dtype}')


Data Value is [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] and type float64
Data Value is [[1 1 1]
 [1 1 1]
 [1 1 1]] and type int64
Data Value is [['1.0' '1.0' '1.0']
 ['1.0' '1.0' '1.0']
 ['1.0' '1.0' '1.0']] and type <U32


In [13]:
''' Test 8 
- like a loop in plain python
- keyword is : 'arange' 
- Three Peremater: Start , Stop , Step
'''
test8=np.arange(start=1,stop=11,step=1)
print(test8)
print(type(test8))


[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [14]:
''' test 9 
- keyword is :linspace
- Three peremeter:Start, Stop, num
'''
test9=np.linspace(start=1,stop=11,num=5)
print(test9)
print(type(test9))

[ 1.   3.5  6.   8.5 11. ]
<class 'numpy.ndarray'>
